# Clase 1 - Introducción a pandas

En este notebook vamos a ver una introducción a los comandos iniciales de la biblioteca pandas para Python. [Pandas](https://pandas.pydata.org) es una biblioteca sponsoreada por [NumFOCUS](https://numfocus.org/sponsored-projects).

La descripción en su página la define como:

> pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

# Estructuras de datos

Dos estructuras fundamentales dentro de pandas son Series y DataFrames. Los dataframes son tablas de datos. Cada columna es una Series.

Para comenzar, vamos a crear nuestro primer DataFrame a partir de un archivo CSV que contiene un [dataset sobre superhéroes](https://www.kaggle.com/claudiodavi/superhero-set/home).

In [1]:
from collections import Counter
import requests

Empezamos por descargarlo del drive de la materia.

In [2]:
with requests.get(
    "https://docs.google.com/spreadsheets/d/1nuJAaaH_IP8Q80CsyS940EVaePkbmqhN3vlorDxYMnA/export?format=csv"
) as r, open("superheroes.csv", "wb") as f:
    for chunk in r.iter_content():
        f.write(chunk)

In [3]:
import pandas as pd

df = pd.read_csv("superheroes.csv")

También podemos crear dataframes desde listas, diccionarios y otras estructuras.

## Inspeccionando un dataframe

In [4]:
# vemos los primeros elementos
df.head()

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,-,good,441.0
1,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
2,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0
3,Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,-,bad,441.0
4,Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,-,bad,-99.0

In [5]:
df.tail()

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
729,Yellowjacket II,Female,blue,Human,Strawberry Blond,165.0,Marvel Comics,-,good,52.0
730,Ymir,Male,white,Frost Giant,No Hair,304.8,Marvel Comics,white,good,-99.0
731,Yoda,Male,brown,Yoda's species,White,66.0,George Lucas,green,good,17.0
732,Zatanna,Female,blue,Human,Black,170.0,DC Comics,-,good,57.0
733,Zoom,Male,red,-,Brown,185.0,DC Comics,-,bad,81.0

In [6]:
df.sample()

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
623,Spider-Man,-,red,Human,Brown,178.0,Marvel Comics,-,good,77.0

In [7]:
df.sample(10)

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
394,Kraven II,Male,brown,Human,Black,191.0,Marvel Comics,-,bad,99.0
459,Mister Mxyzptlk,Male,-,God / Eternal,-,-99.0,DC Comics,-,bad,-99.0
198,Danny Cooper,Male,brown,-,Blond,-99.0,HarperCollins,-,good,-99.0
498,Odin,Male,blue,God / Eternal,White,206.0,Marvel Comics,-,good,293.0
701,Vixen,Female,amber,Human,Black,175.0,DC Comics,-,good,63.0
202,Darkman,Male,-,-,-,-99.0,Universal Studios,-,good,-99.0
327,Hobgoblin,Male,blue,-,Grey,180.0,Marvel Comics,-,bad,83.0
691,Venom III,Male,brown,Symbiote,Brown,229.0,Marvel Comics,-,bad,334.0
104,Black Manta,Male,black,Human,No Hair,188.0,DC Comics,-,bad,92.0
296,Greedo,Male,purple,Rodian,-,170.0,George Lucas,green,bad,-99.0

## Información sobre un dataframe

In [8]:
# descripción de cada columna e información general del dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 734 entries, 0 to 733
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        734 non-null    object
 1   Gender      734 non-null    object
 2   Eye color   734 non-null    object
 3   Race        734 non-null    object
 4   Hair color  734 non-null    object
 5   Height      734 non-null    float64
 6   Publisher   719 non-null    object
 7   Skin color  734 non-null    object
 8   Alignment   734 non-null    object
 9   Weight      732 non-null    float64
dtypes: float64(2), object(8)
memory usage: 57.5+ KB

La última columna, `Dtype` nos dice qué tipo de dato interpreta pandas que es esa columna. Las columnas de tipo `str` son interpretadas con `dtype` del tipo `object`.

In [9]:
# resumen estadístico de las columnas numéricas
df.describe()

           Height      Weight
count  734.000000  732.000000
mean   102.254087   43.855191
std    139.624543  130.823733
min    -99.000000  -99.000000
25%    -99.000000  -99.000000
50%    175.000000   62.000000
75%    185.000000   90.000000
max    975.000000  900.000000

In [10]:
# si queremos ver la cantidad de nulos en cada columna
# creamos una máscara binaria y la sumamos
df.isnull().sum()

name           0
Gender         0
Eye color      0
Race           0
Hair color     0
Height         0
Publisher     15
Skin color     0
Alignment      0
Weight         2
dtype: int64

# Cómo obtener valores que nos interesan

## Por índices

In [11]:
df.index

RangeIndex(start=0, stop=734, step=1)

In [12]:
df = df.set_index('name')
df

,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
name,,,,,,,,,
A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,-,good,441.0
Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0
Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,-,bad,441.0
Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,-,bad,-99.0
...,...,...,...,...,...,...,...,...,...
Yellowjacket II,Female,blue,Human,Strawberry Blond,165.0,Marvel Comics,-,good,52.0
Ymir,Male,white,Frost Giant,No Hair,304.8,Marvel Comics,white,good,-99.0
Yoda,Male,brown,Yoda's species,White,66.0,George Lucas,green,good,17.0
Zatanna,Female,blue,Human,Black,170.0,DC Comics,-,good,57.0
Zoom,Male,red,-,Brown,185.0,DC Comics,-,bad,81.0

In [13]:
df.index

Index(['A-Bomb', 'Abe Sapien', 'Abin Sur', 'Abomination', 'Abraxas',
       'Absorbing Man', 'Adam Monroe', 'Adam Strange', 'Agent 13', 'Agent Bob',
       ...
       'Wyatt Wingfoot', 'X-23', 'X-Man', 'Yellow Claw', 'Yellowjacket',
       'Yellowjacket II', 'Ymir', 'Yoda', 'Zatanna', 'Zoom'],
      dtype='object', name='name', length=734)

In [14]:
hero = df.loc['Aurora']

hero

Gender               Female
Eye color              blue
Race                 Mutant
Hair color            Black
Height                  180
Publisher     Marvel Comics
Skin color                -
Alignment              good
Weight                   63
Name: Aurora, dtype: object

In [15]:
hero = df.iloc[55]

hero

Gender               Female
Eye color              blue
Race                 Mutant
Hair color            Black
Height                  180
Publisher     Marvel Comics
Skin color                -
Alignment              good
Weight                   63
Name: Aurora, dtype: object

In [16]:
heroes = df.loc['Aurora':'Banshee']

heroes

,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
name,,,,,,,,,
Aurora,Female,blue,Mutant,Black,180.0,Marvel Comics,-,good,63.0
Azazel,Male,yellow,Neyaphem,Black,183.0,Marvel Comics,red,bad,67.0
Azrael,Male,brown,Human,Black,-99.0,DC Comics,-,good,-99.0
Aztar,Male,-,-,-,-99.0,DC Comics,-,good,-99.0
Bane,Male,-,Human,-,203.0,DC Comics,-,bad,180.0
Banshee,Male,green,Human,Strawberry Blond,183.0,Marvel Comics,-,good,77.0

In [17]:
heroes = df.iloc[55:60]

heroes

,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
name,,,,,,,,,
Aurora,Female,blue,Mutant,Black,180.0,Marvel Comics,-,good,63.0
Azazel,Male,yellow,Neyaphem,Black,183.0,Marvel Comics,red,bad,67.0
Azrael,Male,brown,Human,Black,-99.0,DC Comics,-,good,-99.0
Aztar,Male,-,-,-,-99.0,DC Comics,-,good,-99.0
Bane,Male,-,Human,-,203.0,DC Comics,-,bad,180.0

## Obtener columnas

In [18]:
df.Race

name
A-Bomb                         Human
Abe Sapien             Icthyo Sapien
Abin Sur                     Ungaran
Abomination        Human / Radiation
Abraxas                Cosmic Entity
                         ...
Yellowjacket II                Human
Ymir                     Frost Giant
Yoda                  Yoda's species
Zatanna                        Human
Zoom                               -
Name: Race, Length: 734, dtype: object

In [19]:
df['Race']

name
A-Bomb                         Human
Abe Sapien             Icthyo Sapien
Abin Sur                     Ungaran
Abomination        Human / Radiation
Abraxas                Cosmic Entity
                         ...
Yellowjacket II                Human
Ymir                     Frost Giant
Yoda                  Yoda's species
Zatanna                        Human
Zoom                               -
Name: Race, Length: 734, dtype: object

## Obtener un subconjunto de columnas

In [20]:
df[['Race', 'Skin color']]

                              Race Skin color
name
A-Bomb                       Human          -
Abe Sapien           Icthyo Sapien       blue
Abin Sur                   Ungaran        red
Abomination      Human / Radiation          -
Abraxas              Cosmic Entity          -
...                            ...        ...
Yellowjacket II              Human          -
Ymir                   Frost Giant      white
Yoda                Yoda's species      green
Zatanna                      Human          -
Zoom                             -          -

[734 rows x 2 columns]

## Obtener filas

In [21]:
condition = df['Skin color'] == 'blue'

In [22]:
condition.head()

name
A-Bomb         False
Abe Sapien      True
Abin Sur       False
Abomination    False
Abraxas        False
Name: Skin color, dtype: bool

Si ahora queremos filtrar y quedarnos solamente con los datos que cumplen la condición:

In [23]:
df[df['Skin color'] == 'blue']

,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
name,,,,,,,,,
Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
Archangel,Male,blue,Mutant,Blond,183.0,Marvel Comics,blue,good,68.0
Beast,Male,blue,Mutant,Blue,180.0,Marvel Comics,blue,good,181.0
Copycat,Female,red,Mutant,White,183.0,Marvel Comics,blue,neutral,67.0
Dr Manhattan,Male,white,Human / Cosmic,No Hair,-99.0,DC Comics,blue,good,-99.0
Killer Frost,Female,blue,Human,Blond,-99.0,DC Comics,blue,bad,-99.0
Mystique,Female,yellow (without irises),Mutant,Red / Orange,178.0,Marvel Comics,blue,bad,54.0
Nebula,Female,blue,Luphomoid,No Hair,185.0,Marvel Comics,blue,bad,83.0
Shadow Lass,Female,black,Talokite,Black,173.0,DC Comics,blue,good,54.0

## Múltiples condiciones

In [24]:
df[(df['Skin color'] == 'blue') & (df['Publisher'] == 'Marvel Comics')]

,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
name,,,,,,,,,
Archangel,Male,blue,Mutant,Blond,183.0,Marvel Comics,blue,good,68.0
Beast,Male,blue,Mutant,Blue,180.0,Marvel Comics,blue,good,181.0
Copycat,Female,red,Mutant,White,183.0,Marvel Comics,blue,neutral,67.0
Mystique,Female,yellow (without irises),Mutant,Red / Orange,178.0,Marvel Comics,blue,bad,54.0
Nebula,Female,blue,Luphomoid,No Hair,185.0,Marvel Comics,blue,bad,83.0

In [25]:
df[(df['Skin color'] == 'blue') | (df['Skin color'] == 'green')].sample(10)

,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
name,,,,,,,,,
Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
Beast Boy,Male,green,Human,Green,173.0,DC Comics,green,good,68.0
Drax the Destroyer,Male,red,Human / Altered,No Hair,193.0,Marvel Comics,green,good,306.0
Evilhawk,Male,red,Alien,Black,191.0,Marvel Comics,green,bad,106.0
Hulk,Male,green,Human / Radiation,Green,244.0,Marvel Comics,green,good,630.0
Mantis,Female,green,Human-Kree,Black,168.0,Marvel Comics,green,good,52.0
Poison Ivy,Female,green,Human,Red,168.0,DC Comics,green,bad,50.0
Beast,Male,blue,Mutant,Blue,180.0,Marvel Comics,blue,good,181.0
Michelangelo,Male,blue,Mutant,-,-99.0,IDW Publishing,green,good,-99.0
Dr Manhattan,Male,white,Human / Cosmic,No Hair,-99.0,DC Comics,blue,good,-99.0

# Transformaciones de datos

## Apply

Mediante apply podemos aplicar una función definida aparte a nuestro set de datos

In [26]:
def rate_height(height):
    if height >= 200:
        return "Tall"
    else:
        return "Not tall"

In [27]:
altos = df['Height'].apply(rate_height)
altos

name
A-Bomb                 Tall
Abe Sapien         Not tall
Abin Sur           Not tall
Abomination            Tall
Abraxas            Not tall
                     ...
Yellowjacket II    Not tall
Ymir                   Tall
Yoda               Not tall
Zatanna            Not tall
Zoom               Not tall
Name: Height, Length: 734, dtype: object

Aprovechamos a ver como asignar una nueva columna

In [28]:
df['Tallness'] = df['Height'].apply(rate_height)

In [29]:
df

,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight,Tallness
name,,,,,,,,,,
A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,-,good,441.0,Tall
Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0,Not tall
Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0,Not tall
Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,-,bad,441.0,Tall
Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,-,bad,-99.0,Not tall
...,...,...,...,...,...,...,...,...,...,...
Yellowjacket II,Female,blue,Human,Strawberry Blond,165.0,Marvel Comics,-,good,52.0,Not tall
Ymir,Male,white,Frost Giant,No Hair,304.8,Marvel Comics,white,good,-99.0,Tall
Yoda,Male,brown,Yoda's species,White,66.0,George Lucas,green,good,17.0,Not tall
Zatanna,Female,blue,Human,Black,170.0,DC Comics,-,good,57.0,Not tall
Zoom,Male,red,-,Brown,185.0,DC Comics,-,bad,81.0,Not tall

## Replace

Vemos por ejemplo que 'Skin color' usa '-' para indicar valores vacíos. Corrijamos esto.

In [30]:
df['Skin color'].replace({"-": None}, inplace=True)

In [31]:
df['Skin color']

name
A-Bomb              None
Abe Sapien          blue
Abin Sur             red
Abomination         None
Abraxas             None
                   ...
Yellowjacket II     None
Ymir               white
Yoda               green
Zatanna             None
Zoom                None
Name: Skin color, Length: 734, dtype: object

## Eliminar filas con nulos

In [32]:
df

,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight,Tallness
name,,,,,,,,,,
A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,None,good,441.0,Tall
Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0,Not tall
Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0,Not tall
Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,None,bad,441.0,Tall
Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,None,bad,-99.0,Not tall
...,...,...,...,...,...,...,...,...,...,...
Yellowjacket II,Female,blue,Human,Strawberry Blond,165.0,Marvel Comics,None,good,52.0,Not tall
Ymir,Male,white,Frost Giant,No Hair,304.8,Marvel Comics,white,good,-99.0,Tall
Yoda,Male,brown,Yoda's species,White,66.0,George Lucas,green,good,17.0,Not tall
Zatanna,Female,blue,Human,Black,170.0,DC Comics,None,good,57.0,Not tall
Zoom,Male,red,-,Brown,185.0,DC Comics,None,bad,81.0,Not tall

In [33]:
df = df.dropna(subset=['Skin color'])
df

,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight,Tallness
name,,,,,,,,,,
Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0,Not tall
Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0,Not tall
Alien,Male,-,Xenomorph XX121,No Hair,244.0,Dark Horse Comics,black,bad,169.0,Tall
Apocalypse,Male,red,Mutant,Black,213.0,Marvel Comics,grey,bad,135.0,Tall
Archangel,Male,blue,Mutant,Blond,183.0,Marvel Comics,blue,good,68.0,Not tall
...,...,...,...,...,...,...,...,...,...,...
Triton,Male,green,Inhuman,No Hair,188.0,Marvel Comics,green,good,86.0,Not tall
Ultron,Male,red,Android,-,206.0,Marvel Comics,silver,bad,331.0,Tall
Vision,Male,gold,Android,No Hair,191.0,Marvel Comics,red,good,135.0,Not tall
Ymir,Male,white,Frost Giant,No Hair,304.8,Marvel Comics,white,good,-99.0,Tall
Yoda,Male,brown,Yoda's species,White,66.0,George Lucas,green,good,17.0,Not tall

# Unir información de distintas tablas

Veamos si hay razas que tengan el mismo color de piel.

In [34]:
df.merge(df, left_on='Skin color', right_on='Skin color')[['Race_x', 'Race_y']]

            Race_x          Race_y
0    Icthyo Sapien   Icthyo Sapien
1    Icthyo Sapien          Mutant
2    Icthyo Sapien          Mutant
3    Icthyo Sapien          Mutant
4    Icthyo Sapien  Human / Cosmic
..             ...             ...
729        Eternal         Eternal
730         Gungan          Gungan
731        Android         Android
732       Czarnian        Czarnian
733     Tamaranean      Tamaranean

[734 rows x 2 columns]

Tenemos duplicados!

In [35]:
df.merge(df, left_on='Skin color', right_on='Skin color')[['Race_x', 'Race_y']]

            Race_x          Race_y
0    Icthyo Sapien   Icthyo Sapien
1    Icthyo Sapien          Mutant
2    Icthyo Sapien          Mutant
3    Icthyo Sapien          Mutant
4    Icthyo Sapien  Human / Cosmic
..             ...             ...
729        Eternal         Eternal
730         Gungan          Gungan
731        Android         Android
732       Czarnian        Czarnian
733     Tamaranean      Tamaranean

[734 rows x 2 columns]

Tenemos que sacar los que son iguales en ambas columnas!

In [36]:
same_skin_color = df.merge(df, left_on='Skin color', right_on='Skin color')[
    ['Race_x', 'Race_y']
].drop_duplicates()
same_skin_color[same_skin_color.Race_x != same_skin_color.Race_y]

            Race_x          Race_y
1    Icthyo Sapien          Mutant
4    Icthyo Sapien  Human / Cosmic
5    Icthyo Sapien           Human
7    Icthyo Sapien       Luphomoid
8    Icthyo Sapien        Talokite
..             ...             ...
723      Strontian         Eternal
724          Human       Strontian
726          Human         Eternal
727        Eternal       Strontian
728        Eternal           Human

[372 rows x 2 columns]

In [37]:
pd.merge?

In [38]:
df1 = pd.DataFrame({'col': [1, 2, 3], 'val': [10, 11, 12]})
df2 = pd.DataFrame({'col': [2, 3, 4], 'val': [13, 14, 15]})

In [39]:
df1

   col  val
0    1   10
1    2   11
2    3   12

In [40]:
df2

   col  val
0    2   13
1    3   14
2    4   15

In [41]:
pd.merge(df1, df2, how='left', left_on='col', right_on='col')

   col  val_x  val_y
0    1     10    NaN
1    2     11   13.0
2    3     12   14.0

In [42]:
pd.merge(df1, df2, how='inner', left_on='col', right_on='col')

   col  val_x  val_y
0    2     11     13
1    3     12     14

In [43]:
pd.merge(df1, df2, how='right', left_on='col', right_on='col')

   col  val_x  val_y
0    2   11.0     13
1    3   12.0     14
2    4    NaN     15

In [44]:
pd.merge(df1, df2, how='outer', left_on='col', right_on='col')

   col  val_x  val_y
0    1   10.0    NaN
1    2   11.0   13.0
2    3   12.0   14.0
3    4    NaN   15.0

In [45]:
df1.merge?

In [46]:
df1.join?

Por último, para ver los pares únicos

In [47]:
same_skin_color = df.merge(df, left_on='Skin color', right_on='Skin color')[
    ['Race_x', 'Race_y']
].drop_duplicates()
same_skin_color[
    (same_skin_color.Race_x != same_skin_color.Race_y)
    & (same_skin_color.Race_x > same_skin_color.Race_y)
]

            Race_x          Race_y
4    Icthyo Sapien  Human / Cosmic
5    Icthyo Sapien           Human
9           Mutant   Icthyo Sapien
13          Mutant  Human / Cosmic
14          Mutant           Human
..             ...             ...
708         Cyborg         Android
719         Mutant           Demon
722      Strontian           Human
723      Strontian         Eternal
726          Human         Eternal

[186 rows x 2 columns]

### Concatenar tablas

In [48]:
df_1 = pd.DataFrame({'col_1': range(1, 10), 'col_2': range(1, 10)})
df_2 = pd.DataFrame({'col_1': range(11, 20), 'col_2': range(11, 20)})

In [49]:
df_1.pipe(len)

9

In [50]:
df_2.pipe(len)

9

In [51]:
df_1.head()

   col_1  col_2
0      1      1
1      2      2
2      3      3
3      4      4
4      5      5

In [52]:
df_2.head()

   col_1  col_2
0     11     11
1     12     12
2     13     13
3     14     14
4     15     15

In [53]:
df_concat = pd.concat([df_1, df_2])
df_concat

   col_1  col_2
0      1      1
1      2      2
2      3      3
3      4      4
4      5      5
5      6      6
6      7      7
7      8      8
8      9      9
0     11     11
1     12     12
2     13     13
3     14     14
4     15     15
5     16     16
6     17     17
7     18     18
8     19     19

In [54]:
df_concat.pipe(len)

18

# Agrupaciones

## Groupby

In [55]:
# queremos ver los nombres
df = df.reset_index()

In [56]:
df

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight,Tallness
0,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0,Not tall
1,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0,Not tall
2,Alien,Male,-,Xenomorph XX121,No Hair,244.0,Dark Horse Comics,black,bad,169.0,Tall
3,Apocalypse,Male,red,Mutant,Black,213.0,Marvel Comics,grey,bad,135.0,Tall
4,Archangel,Male,blue,Mutant,Blond,183.0,Marvel Comics,blue,good,68.0,Not tall
...,...,...,...,...,...,...,...,...,...,...,...
67,Triton,Male,green,Inhuman,No Hair,188.0,Marvel Comics,green,good,86.0,Not tall
68,Ultron,Male,red,Android,-,206.0,Marvel Comics,silver,bad,331.0,Tall
69,Vision,Male,gold,Android,No Hair,191.0,Marvel Comics,red,good,135.0,Not tall
70,Ymir,Male,white,Frost Giant,No Hair,304.8,Marvel Comics,white,good,-99.0,Tall
71,Yoda,Male,brown,Yoda's species,White,66.0,George Lucas,green,good,17.0,Not tall

In [57]:
df.groupby("Race")

In [58]:
df.groupby("Race").agg(list)

,name,Gender,Eye color,Hair color,Height,Publisher,Skin color,Alignment,Weight,Tallness
Race,,,,,,,,,,
-,"[Kool-Aid Man, Man-Thing]","[Male, Male]","[black, red]","[No Hair, No Hair]","[-99.0, 213.0]","[nan, Marvel Comics]","[red, green]","[good, good]","[-99.0, 225.0]","[Not tall, Tall]"
Alien,"[Ardina, Century, Evilhawk, Silver Surfer]","[Female, Male, Male, Male]","[white, white, red, white]","[Orange, White, Black, No Hair]","[193.0, 201.0, 191.0, 193.0]","[Marvel Comics, Marvel Comics, Marvel Comics, ...","[gold, grey, green, silver]","[good, good, bad, good]","[98.0, 97.0, 106.0, 101.0]","[Not tall, Tall, Not tall, Not tall]"
Android,"[Brainiac, K-2SO, T-1000, Ultron, Vision]","[Male, Male, Male, Male, Male]","[green, white, -, red, gold]","[No Hair, No Hair, -, -, No Hair]","[198.0, 213.0, 183.0, 206.0, 191.0]","[DC Comics, George Lucas, Dark Horse Comics, M...","[green, gray, silver, silver, red]","[bad, good, bad, bad, good]","[135.0, -99.0, 146.0, 331.0, 135.0]","[Not tall, Tall, Not tall, Tall, Not tall]"
Bizarro,[Bizarro],[Male],[black],[Black],[191.0],[DC Comics],[white],[neutral],[155.0],[Not tall]
Bolovaxian,[Kilowog],[Male],[red],[No Hair],[234.0],[DC Comics],[pink],[good],[324.0],[Tall]
Cosmic Entity,[Living Tribunal],[-],[blue],[No Hair],[-99.0],[Marvel Comics],[gold],[neutral],[-99.0],[Not tall]
Cyborg,[T-X],[Female],[-],[-],[-99.0],[Dark Horse Comics],[silver],[bad],[149.0],[Not tall]
Czarnian,[Lobo],[Male],[red],[Black],[229.0],[DC Comics],[blue-white],[neutral],[288.0],[Tall]
Dathomirian Zabrak,[Darth Maul],[Male],[yellow / red],[-],[170.0],[George Lucas],[red / black],[bad],[-99.0],[Not tall]
Demon,"[Blackout, Etrigan]","[Male, Male]","[red, red]","[White, No Hair]","[191.0, 193.0]","[Marvel Comics, DC Comics]","[white, yellow]","[bad, neutral]","[104.0, 203.0]","[Not tall, Not tall]"
Eternal,[Thanos],[Male],[red],[No Hair],[201.0],[Marvel Comics],[purple],[bad],[443.0],[Tall]
Frost Giant,[Ymir],[Male],[white],[No Hair],[304.8],[Marvel Comics],[white],[good],[-99.0],[Tall]
God / Eternal,"[Spectre, Swamp Thing, Trigon]","[Male, Male, Male]","[white, red, yellow]","[No Hair, No Hair, Black]","[-99.0, -99.0, -99.0]","[DC Comics, DC Comics, DC Comics]","[white, green, red]","[good, bad, bad]","[-99.0, -99.0, -99.0]","[Not tall, Not tall, Not tall]"
Gungan,[Jar Jar Binks],[Male],[yellow],[-],[193.0],[George Lucas],[orange / white],[good],[-99.0],[Not tall]
Human,"[Beast Boy, Domino, Joker, Killer Frost, Klaw,...","[Male, Female, Male, Female, Male, Female, Mal...","[green, blue, green, blue, red, green, purple,...","[Green, Black, Green, Blond, No Hair, Red, Pur...","[173.0, 173.0, 196.0, -99.0, 188.0, 168.0, 180...","[DC Comics, Marvel Comics, DC Comics, DC Comic...","[green, white, white, blue, red, green, purple...","[good, good, bad, bad, bad, bad, bad, bad]","[68.0, 54.0, 86.0, -99.0, 97.0, 50.0, 74.0, 20...","[Not tall, Not tall, Not tall, Not tall, Not t..."
Human / Altered,[Drax the Destroyer],[Male],[red],[No Hair],[193.0],[Marvel Comics],[green],[good],[306.0],[Not tall]
Human / Cosmic,"[Dr Manhattan, Nova]","[Male, Female]","[white, white]","[No Hair, Red]","[-99.0, 163.0]","[DC Comics, Marvel Comics]","[blue, gold]","[good, good]","[-99.0, 59.0]","[Not tall, Not tall]"
Human / Radiation,"[Captain Atom, Hulk, Red Hulk]","[Male, Male, Male]","[blue, green, yellow]","[Silver, Green, Black]","[193.0, 244.0, 213.0]","[DC Comics, Marvel Comics, Marvel Comics]","[silver, green, red]","[good, good, neutral]","[90.0, 630.0, 630.0]","[Not tall, Tall, Tall]"
Human-Kree,[Mantis],[Female],[green],[Black],[168.0],[Marvel Comics],[green],[good],[52.0],[Not tall]
Icthyo Sapien,[Abe Sapien],[Male],[blue],[No Hair],[191.0],[Dark Horse Comics],[blue],[good],[65.0],[Not tall]
Inhuman,[Triton],[Male],[green],[No Hair],[188.0],[Marvel Comics],[green],[good],[86.0],[Not tall]
Kaiju,[Godzilla],[-],[-],[-],[108.0],[nan],[grey],[bad],[nan],[Not tall]
Kakarantharaian,[Fin Fang Foom],[Male],[red],[No Hair],[975.0],[Marvel Comics],[green],[good],[18.0],[Tall]
Korugaran,[Sinestro],[Male],[black],[Black],[201.0],[DC Comics],[red],[neutral],[92.0],[Tall]
Luphomoid,[Nebula],[Female],[blue],[No Hair],[185.0],[Marvel Comics],[blue],[bad],[83.0],[Not tall]
Martian,[Martian Manhunter],[Male],[red],[No Hair],[201.0],[DC Comics],[green],[good],[135.0],[Tall]
Metahuman,[Killer Croc],[Male],[red],[No Hair],[244.0],[DC Comics],[green],[bad],[356.0],[Tall]
Mutant,"[Apocalypse, Archangel, Beast, Blink, Copycat,...","[Male, Male, Male, Female, Female, Male, Male,...","[red, blue, blue, green, red, green, blue, blu...","[Black, Blond, Blue, Magenta, White, No Hair, ...","[213.0, 183.0, 180.0, 165.0, 183.0, -99.0, 183...","[Marvel Comics, Marvel Comics, Marvel Comics, ...","[grey, blue, blue, pink, blue, green, red, gre...","[bad, good, good, good, neutral, good, bad, go...","[135.0, 68.0, 181.0, 56.0, 67.0, -99.0, 88.0, ...","[Tall, Not tall, Not tall, Not tall, Not tall,..."
New God,"[Darkseid, Steppenwolf]","[Male, Male]","[red, red]","[No Hair, Black]","[267.0, 183.0]","[DC Comics, DC Comics]","[grey, white]","[bad, bad]","[817.0, 91.0]","[Tall, Not tall]"
Neyaphem,[Azazel],[Male],[yellow],[Black],[183.0],[Marvel Comics],[red],[bad],[67.0],[Not tall]
Rodian,[Greedo],[Male],[purple],[-],[170.0],[George Lucas],[green],[bad],[-99.0],[Not tall]
Strontian,[Gladiator],[Male],[blue],[Blue],[198.0],[Marvel Comics],[purple],[neutral],[268.0],[Not tall]
Talokite,[Shadow Lass],[Female],[black],[Black],[173.0],[DC Comics],[blue],[good],[54.0],[Not tall]
Tamaranean,[Starfire],[Female],[green],[Auburn],[193.0],[DC Comics],[orange],[good],[71.0],[Not tall]
Ungaran,[Abin Sur],[Male],[blue],[No Hair],[185.0],[DC Comics],[red],[good],[90.0],[Not tall]
Xenomorph XX121,[Alien],[Male],[-],[No Hair],[244.0],[Dark Horse Comics],[black],[bad],[169.0],[Tall]
Yoda's species,[Yoda],[Male],[brown],[White],[66.0],[George Lucas],[green],[good],[17.0],[Not tall]
Zen-Whoberian,[Gamora],[Female],[yellow],[Black],[183.0],[Marvel Comics],[green],[good],[77.0],[Not tall]

In [59]:
(df['Alignment'] == 'good').mean() * 100

48.61111111111111

In [60]:
(df['Alignment'] == 'good').sum() / (df['Alignment'] == 'good').size

0.4861111111111111

In [61]:
df.groupby("Race")['Alignment'].apply(len)

Race
-                      2
Alien                  4
Android                5
Bizarro                1
Bolovaxian             1
Cosmic Entity          1
Cyborg                 1
Czarnian               1
Dathomirian Zabrak     1
Demon                  2
Eternal                1
Frost Giant            1
God / Eternal          3
Gungan                 1
Human                  8
Human / Altered        1
Human / Cosmic         2
Human / Radiation      3
Human-Kree             1
Icthyo Sapien          1
Inhuman                1
Kaiju                  1
Kakarantharaian        1
Korugaran              1
Luphomoid              1
Martian                1
Metahuman              1
Mutant                13
New God                2
Neyaphem               1
Rodian                 1
Strontian              1
Talokite               1
Tamaranean             1
Ungaran                1
Xenomorph XX121        1
Yoda's species         1
Zen-Whoberian          1
Name: Alignment, dtype: int64

In [62]:
def perc_good(grouping):
    """Devuelve el porcentaje que son 'good'."""
    return (grouping == 'good').mean() * 100.0


df.groupby("Race").agg(
    {
        'name': 'count',
        'Height': ['mean', 'std'],
        'Weight': ['mean', 'std'],
        'Alignment': perc_good,
    }
).head(20)

                    name      Height               Weight              \
                   count        mean         std     mean         std
Race
-                      2   57.000000  220.617316   63.000  229.102597
Alien                  4  194.500000    4.434712  100.500    4.041452
Android                5  198.200000   11.861703  129.600  152.600131
Bizarro                1  191.000000         NaN  155.000         NaN
Bolovaxian             1  234.000000         NaN  324.000         NaN
Cosmic Entity          1  -99.000000         NaN  -99.000         NaN
Cyborg                 1  -99.000000         NaN  149.000         NaN
Czarnian               1  229.000000         NaN  288.000         NaN
Dathomirian Zabrak     1  170.000000         NaN  -99.000         NaN
Demon                  2  192.000000    1.414214  153.500   70.003571
Eternal                1  201.000000         NaN  443.000         NaN
Frost Giant            1  304.800000         NaN  -99.000         NaN
God / Eternal          3  -99.000000    0.000000  -99.000    0.000000
Gungan                 1  193.000000         NaN  -99.000         NaN
Human                  8  145.500000   99.215494   66.625   82.652349
Human / Altered        1  193.000000         NaN  306.000         NaN
Human / Cosmic         2   32.000000  185.261977  -20.000  111.722871
Human / Radiation      3  216.666667   25.696952  450.000  311.769145
Human-Kree             1  168.000000         NaN   52.000         NaN
Icthyo Sapien          1  191.000000         NaN   65.000         NaN

                     Alignment
                     perc_good
Race
-                   100.000000
Alien                75.000000
Android              40.000000
Bizarro               0.000000
Bolovaxian          100.000000
Cosmic Entity         0.000000
Cyborg                0.000000
Czarnian              0.000000
Dathomirian Zabrak    0.000000
Demon                 0.000000
Eternal               0.000000
Frost Giant         100.000000
God / Eternal        33.333333
Gungan              100.000000
Human                25.000000
Human / Altered     100.000000
Human / Cosmic      100.000000
Human / Radiation    66.666667
Human-Kree          100.000000
Icthyo Sapien       100.000000

Algunas agregaciones tienen métodos para realizarlos directamente

In [63]:
df.Race.value_counts()

Mutant                13
Human                  8
Android                5
Alien                  4
Human / Radiation      3
God / Eternal          3
-                      2
Demon                  2
New God                2
Human / Cosmic         2
Rodian                 1
Inhuman                1
Human-Kree             1
Xenomorph XX121        1
Kaiju                  1
Luphomoid              1
Human / Altered        1
Zen-Whoberian          1
Korugaran              1
Dathomirian Zabrak     1
Yoda's species         1
Talokite               1
Icthyo Sapien          1
Strontian              1
Neyaphem               1
Czarnian               1
Cyborg                 1
Martian                1
Cosmic Entity          1
Gungan                 1
Eternal                1
Tamaranean             1
Kakarantharaian        1
Bizarro                1
Frost Giant            1
Ungaran                1
Bolovaxian             1
Metahuman              1
Name: Race, dtype: int64

Y si lo queremos como porcentajes?

In [64]:
df.Race.value_counts() / df.Race.value_counts().sum() * 100

Mutant                18.055556
Human                 11.111111
Android                6.944444
Alien                  5.555556
Human / Radiation      4.166667
God / Eternal          4.166667
-                      2.777778
Demon                  2.777778
New God                2.777778
Human / Cosmic         2.777778
Rodian                 1.388889
Inhuman                1.388889
Human-Kree             1.388889
Xenomorph XX121        1.388889
Kaiju                  1.388889
Luphomoid              1.388889
Human / Altered        1.388889
Zen-Whoberian          1.388889
Korugaran              1.388889
Dathomirian Zabrak     1.388889
Yoda's species         1.388889
Talokite               1.388889
Icthyo Sapien          1.388889
Strontian              1.388889
Neyaphem               1.388889
Czarnian               1.388889
Cyborg                 1.388889
Martian                1.388889
Cosmic Entity          1.388889
Gungan                 1.388889
Eternal                1.388889
Tamaranean             1.388889
Kakarantharaian        1.388889
Bizarro                1.388889
Frost Giant            1.388889
Ungaran                1.388889
Bolovaxian             1.388889
Metahuman              1.388889
Name: Race, dtype: float64

In [65]:
df.Race.value_counts(normalize=True)

Mutant                0.180556
Human                 0.111111
Android               0.069444
Alien                 0.055556
Human / Radiation     0.041667
God / Eternal         0.041667
-                     0.027778
Demon                 0.027778
New God               0.027778
Human / Cosmic        0.027778
Rodian                0.013889
Inhuman               0.013889
Human-Kree            0.013889
Xenomorph XX121       0.013889
Kaiju                 0.013889
Luphomoid             0.013889
Human / Altered       0.013889
Zen-Whoberian         0.013889
Korugaran             0.013889
Dathomirian Zabrak    0.013889
Yoda's species        0.013889
Talokite              0.013889
Icthyo Sapien         0.013889
Strontian             0.013889
Neyaphem              0.013889
Czarnian              0.013889
Cyborg                0.013889
Martian               0.013889
Cosmic Entity         0.013889
Gungan                0.013889
Eternal               0.013889
Tamaranean            0.013889
Kakarantharaian       0.013889
Bizarro               0.013889
Frost Giant           0.013889
Ungaran               0.013889
Bolovaxian            0.013889
Metahuman             0.013889
Name: Race, dtype: float64

Veamos como podemos obtener las filas del dataframe original donde la columna `Race` este entre aquellos valores con mas del 5% de repeticiones.

In [66]:
over5 = df.Race.value_counts(normalize=True) > 0.05
mutants_over5 = df.Race.value_counts()[over5]

Teniendo la indexacion, veamos como resolverlo con `isin`

In [67]:
df[df.Race.isin(mutants_over5.index)].head(5)

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight,Tallness
3,Apocalypse,Male,red,Mutant,Black,213.0,Marvel Comics,grey,bad,135.0,Tall
4,Archangel,Male,blue,Mutant,Blond,183.0,Marvel Comics,blue,good,68.0,Not tall
5,Ardina,Female,white,Alien,Orange,193.0,Marvel Comics,gold,good,98.0,Not tall
7,Beast,Male,blue,Mutant,Blue,180.0,Marvel Comics,blue,good,181.0,Not tall
8,Beast Boy,Male,green,Human,Green,173.0,DC Comics,green,good,68.0,Not tall

Alternativamente, con `merge`

In [68]:
df.merge(mutants_over5, left_on='Race', right_index=True, how='inner')

,Race,name,Gender,Eye color,Race_x,Hair color,Height,Publisher,Skin color,Alignment,Weight,Tallness,Race_y
3,Mutant,Apocalypse,Male,red,Mutant,Black,213.0,Marvel Comics,grey,bad,135.0,Tall,13
4,Mutant,Archangel,Male,blue,Mutant,Blond,183.0,Marvel Comics,blue,good,68.0,Not tall,13
7,Mutant,Beast,Male,blue,Mutant,Blue,180.0,Marvel Comics,blue,good,181.0,Not tall,13
11,Mutant,Blink,Female,green,Mutant,Magenta,165.0,Marvel Comics,pink,good,56.0,Not tall,13
15,Mutant,Copycat,Female,red,Mutant,White,183.0,Marvel Comics,blue,neutral,67.0,Not tall,13
19,Mutant,Donatello,Male,green,Mutant,No Hair,-99.0,IDW Publishing,green,good,-99.0,Not tall,13
24,Mutant,Exodus,Male,blue,Mutant,Black,183.0,Marvel Comics,red,bad,88.0,Not tall,13
39,Mutant,Leonardo,Male,blue,Mutant,No Hair,-99.0,IDW Publishing,green,good,-99.0,Not tall,13
45,Mutant,Michelangelo,Male,blue,Mutant,-,-99.0,IDW Publishing,green,good,-99.0,Not tall,13
46,Mutant,Mystique,Female,yellow (without irises),Mutant,Red / Orange,178.0,Marvel Comics,blue,bad,54.0,Not tall,13
51,Mutant,Raphael,Male,-,Mutant,No Hair,-99.0,IDW Publishing,green,good,-99.0,Not tall,13
60,Mutant,Swarm,Male,yellow,Mutant,No Hair,196.0,Marvel Comics,yellow,bad,47.0,Not tall,13
65,Mutant,Toad,Male,black,Mutant,Brown,175.0,Marvel Comics,green,neutral,76.0,Not tall,13
5,Alien,Ardina,Female,white,Alien,Orange,193.0,Marvel Comics,gold,good,98.0,Not tall,4
14,Alien,Century,Male,white,Alien,White,201.0,Marvel Comics,grey,good,97.0,Tall,4
23,Alien,Evilhawk,Male,red,Alien,Black,191.0,Marvel Comics,green,bad,106.0,Not tall,4
54,Alien,Silver Surfer,Male,white,Alien,No Hair,193.0,Marvel Comics,silver,good,101.0,Not tall,4
8,Human,Beast Boy,Male,green,Human,Green,173.0,DC Comics,green,good,68.0,Not tall,8
18,Human,Domino,Female,blue,Human,Black,173.0,Marvel Comics,white,good,54.0,Not tall,8
32,Human,Joker,Male,green,Human,Green,196.0,DC Comics,white,bad,86.0,Not tall,8
35,Human,Killer Frost,Female,blue,Human,Blond,-99.0,DC Comics,blue,bad,-99.0,Not tall,8
37,Human,Klaw,Male,red,Human,No Hair,188.0,Marvel Comics,red,bad,97.0,Not tall,8
49,Human,Poison Ivy,Female,green,Human,Red,168.0,DC Comics,green,bad,50.0,Not tall,8
50,Human,Purple Man,Male,purple,Human,Purple,180.0,Marvel Comics,purple,bad,74.0,Not tall,8
64,Human,Tiger Shark,Male,grey,Human,No Hair,185.0,Marvel Comics,grey,bad,203.0,Not tall,8
12,Android,Brainiac,Male,green,Android,No Hair,198.0,DC Comics,green,bad,135.0,Not tall,5
33,Android,K-2SO,Male,white,Android,No Hair,213.0,George Lucas,gray,good,-99.0,Tall,5
61,Android,T-1000,Male,-,Android,-,183.0,Dark Horse Comics,silver,bad,146.0,Not tall,5
68,Android,Ultron,Male,red,Android,-,206.0,Marvel Comics,silver,bad,331.0,Tall,5
69,Android,Vision,Male,gold,Android,No Hair,191.0,Marvel Comics,red,good,135.0,Not tall,5

## Pivoting

In [69]:
pd.pivot_table(
    df,
    index='Race',
    columns=['Gender'],
    values=['Height', 'Weight', 'Alignment'],
    aggfunc={
        'Height': 'mean',
        'Weight': 'mean',
        'Alignment': lambda x: Counter(x).most_common(1)[0][0],
    },
)

                   Alignment                 Height                          \
Gender                     - Female     Male      -      Female        Male
Race
-                        NaN    NaN     good    NaN         NaN   57.000000
Alien                    NaN   good     good    NaN  193.000000  195.000000
Android                  NaN    NaN      bad    NaN         NaN  198.200000
Bizarro                  NaN    NaN  neutral    NaN         NaN  191.000000
Bolovaxian               NaN    NaN     good    NaN         NaN  234.000000
Cosmic Entity        neutral    NaN      NaN  -99.0         NaN         NaN
Cyborg                   NaN    bad      NaN    NaN  -99.000000         NaN
Czarnian                 NaN    NaN  neutral    NaN         NaN  229.000000
Dathomirian Zabrak       NaN    NaN      bad    NaN         NaN  170.000000
Demon                    NaN    NaN      bad    NaN         NaN  192.000000
Eternal                  NaN    NaN      bad    NaN         NaN  201.000000
Frost Giant              NaN    NaN     good    NaN         NaN  304.800000
God / Eternal            NaN    NaN      bad    NaN         NaN  -99.000000
Gungan                   NaN    NaN     good    NaN         NaN  193.000000
Human                    NaN    bad      bad    NaN   80.666667  184.400000
Human / Altered          NaN    NaN     good    NaN         NaN  193.000000
Human / Cosmic           NaN   good     good    NaN  163.000000  -99.000000
Human / Radiation        NaN    NaN     good    NaN         NaN  216.666667
Human-Kree               NaN   good      NaN    NaN  168.000000         NaN
Icthyo Sapien            NaN    NaN     good    NaN         NaN  191.000000
Inhuman                  NaN    NaN     good    NaN         NaN  188.000000
Kaiju                    bad    NaN      NaN  108.0         NaN         NaN
Kakarantharaian          NaN    NaN     good    NaN         NaN  975.000000
Korugaran                NaN    NaN  neutral    NaN         NaN  201.000000
Luphomoid                NaN    bad      NaN    NaN  185.000000         NaN
Martian                  NaN    NaN     good    NaN         NaN  201.000000
Metahuman                NaN    NaN      bad    NaN         NaN  244.000000
Mutant                   NaN   good     good    NaN  175.333333   73.400000
New God                  NaN    NaN      bad    NaN         NaN  225.000000
Neyaphem                 NaN    NaN      bad    NaN         NaN  183.000000
Rodian                   NaN    NaN      bad    NaN         NaN  170.000000
Strontian                NaN    NaN  neutral    NaN         NaN  198.000000
Talokite                 NaN   good      NaN    NaN  173.000000         NaN
Tamaranean               NaN   good      NaN    NaN  193.000000         NaN
Ungaran                  NaN    NaN     good    NaN         NaN  185.000000
Xenomorph XX121          NaN    NaN      bad    NaN         NaN  244.000000
Yoda's species           NaN    NaN     good    NaN         NaN   66.000000
Zen-Whoberian            NaN   good      NaN    NaN  183.000000         NaN

                   Weight
Gender                  -      Female        Male
Race
-                     NaN         NaN   63.000000
Alien                 NaN   98.000000  101.333333
Android               NaN         NaN  129.600000
Bizarro               NaN         NaN  155.000000
Bolovaxian            NaN         NaN  324.000000
Cosmic Entity       -99.0         NaN         NaN
Cyborg                NaN  149.000000         NaN
Czarnian              NaN         NaN  288.000000
Dathomirian Zabrak    NaN         NaN  -99.000000
Demon                 NaN         NaN  153.500000
Eternal               NaN         NaN  443.000000
Frost Giant           NaN         NaN  -99.000000
God / Eternal         NaN         NaN  -99.000000
Gungan                NaN         NaN  -99.000000
Human                 NaN    1.666667  105.600000
Human / Altered       NaN         NaN  306.000000
Human / Cosmic        NaN   59.000000  -99.000000
Human / Radiation     NaN         NaN  450.000000
Human-Kree            NaN   52.000000         NaN
Icthyo Sapien         NaN         NaN   65.000000
Inhuman               NaN         NaN   86.000000
Kaiju                 NaN         NaN         NaN
Kakarantharaian       NaN         NaN   18.000000
Korugaran             NaN         NaN   92.000000
Luphomoid             NaN   83.000000         NaN
Martian               NaN         NaN  135.000000
Metahuman             NaN         NaN  356.000000
Mutant                NaN   59.000000   19.900000
New God               NaN         NaN  454.000000
Neyaphem              NaN         NaN   67.000000
Rodian                NaN         NaN  -99.000000
Strontian             NaN         NaN  268.000000
Talokite              NaN   54.000000         NaN
Tamaranean            NaN   71.000000         NaN
Ungaran               NaN         NaN   90.000000
Xenomorph XX121       NaN         NaN  169.000000
Yoda's species        NaN         NaN   17.000000
Zen-Whoberian         NaN   77.000000         NaN

# Sobre vistas y columnas

In [70]:
df_marvel = df[df.Publisher == 'Marvel Comics']

In [71]:
def alignment_to_numeric(alignment):
    return {'bad': -1, 'good': 1, 'neutral': 0}[alignment]


df_marvel['numeric_alineation'] = df_marvel.Alignment.apply(alignment_to_numeric)

/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [72]:
df_marvel = df[df.Publisher == 'Marvel Comics'].copy()

In [73]:
df_marvel.loc[:, 'numeric_alineation'] = df_marvel.Alignment.apply(alignment_to_numeric)

In [74]:
df_marvel.head()

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight,Tallness,numeric_alineation
3,Apocalypse,Male,red,Mutant,Black,213.0,Marvel Comics,grey,bad,135.0,Tall,-1
4,Archangel,Male,blue,Mutant,Blond,183.0,Marvel Comics,blue,good,68.0,Not tall,1
5,Ardina,Female,white,Alien,Orange,193.0,Marvel Comics,gold,good,98.0,Not tall,1
6,Azazel,Male,yellow,Neyaphem,Black,183.0,Marvel Comics,red,bad,67.0,Not tall,-1
7,Beast,Male,blue,Mutant,Blue,180.0,Marvel Comics,blue,good,181.0,Not tall,1

In [75]:
df_marvel.numeric_alineation.mean()

0.11428571428571428

Una excelente guía al respecto: [link](https://www.dataquest.io/blog/settingwithcopywarning/)

# Ordenando

In [76]:
df.set_index('name').sort_index()

,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight,Tallness
name,,,,,,,,,,
Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0,Not tall
Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0,Not tall
Alien,Male,-,Xenomorph XX121,No Hair,244.0,Dark Horse Comics,black,bad,169.0,Tall
Apocalypse,Male,red,Mutant,Black,213.0,Marvel Comics,grey,bad,135.0,Tall
Archangel,Male,blue,Mutant,Blond,183.0,Marvel Comics,blue,good,68.0,Not tall
...,...,...,...,...,...,...,...,...,...,...
Triton,Male,green,Inhuman,No Hair,188.0,Marvel Comics,green,good,86.0,Not tall
Ultron,Male,red,Android,-,206.0,Marvel Comics,silver,bad,331.0,Tall
Vision,Male,gold,Android,No Hair,191.0,Marvel Comics,red,good,135.0,Not tall
Ymir,Male,white,Frost Giant,No Hair,304.8,Marvel Comics,white,good,-99.0,Tall
Yoda,Male,brown,Yoda's species,White,66.0,George Lucas,green,good,17.0,Not tall

In [77]:
df.sort_values(by=['Height', 'Weight'], ascending=False)

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight,Tallness
25,Fin Fang Foom,Male,red,Kakarantharaian,No Hair,975.0,Marvel Comics,green,good,18.0,Tall
70,Ymir,Male,white,Frost Giant,No Hair,304.8,Marvel Comics,white,good,-99.0,Tall
16,Darkseid,Male,red,New God,No Hair,267.0,DC Comics,grey,bad,817.0,Tall
30,Hulk,Male,green,Human / Radiation,Green,244.0,Marvel Comics,green,good,630.0,Tall
34,Killer Croc,Male,red,Metahuman,No Hair,244.0,DC Comics,green,bad,356.0,Tall
...,...,...,...,...,...,...,...,...,...,...,...
45,Michelangelo,Male,blue,Mutant,-,-99.0,IDW Publishing,green,good,-99.0,Not tall
51,Raphael,Male,-,Mutant,No Hair,-99.0,IDW Publishing,green,good,-99.0,Not tall
56,Spectre,Male,white,God / Eternal,No Hair,-99.0,DC Comics,white,good,-99.0,Not tall
59,Swamp Thing,Male,red,God / Eternal,No Hair,-99.0,DC Comics,green,bad,-99.0,Not tall
66,Trigon,Male,yellow,God / Eternal,Black,-99.0,DC Comics,red,bad,-99.0,Not tall

# Operaciones de strings

In [78]:
df.name.apply(lambda x: x.lower())

0     abe sapien
1       abin sur
2          alien
3     apocalypse
4      archangel
         ...
67        triton
68        ultron
69        vision
70          ymir
71          yoda
Name: name, Length: 72, dtype: object

Entre [otras](https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html)

# Manejo de fechas

### Timestamp

In [79]:
pd.Timestamp("2020-09-30 04:32:18 PM")

Timestamp('2020-09-30 16:32:18')

### DatetimeIndex

In [80]:
fechas = ['2020-03-20', '2020-03-18', '2020/09/30']
indice_fechas = pd.DatetimeIndex(fechas)
indice_fechas

DatetimeIndex(['2020-03-20', '2020-03-18', '2020-09-30'], dtype='datetime64[ns]', freq=None)

In [81]:
descripciones = ['cuarentena', 'cumpleañito', 'hoy']
desc_serie = pd.Series(data=descripciones, index=indice_fechas)
desc_serie

2020-03-20     cuarentena
2020-03-18    cumpleañito
2020-09-30            hoy
dtype: object

### to_datetime

In [82]:
pd.to_datetime('2020/03/30 17:43:09')

Timestamp('2020-03-30 17:43:09')

In [83]:
pd.to_datetime(fechas)

DatetimeIndex(['2020-03-20', '2020-03-18', '2020-09-30'], dtype='datetime64[ns]', freq=None)

In [84]:
serie_fechas = pd.Series(
    ['September 22nd, 2019', '22, 09, 2020', 'Una fecha', 'Oct 15th, 2020']
)
pd.to_datetime(serie_fechas, errors='coerce')

0   2019-09-22
1   2020-09-22
2          NaT
3   2020-10-15
dtype: datetime64[ns]

### Rangos

In [85]:
rango_de_tiempo = pd.date_range(start='25/06/2019', end='25/06/2020', freq='D')
rango_de_tiempo

DatetimeIndex(['2019-06-25', '2019-06-26', '2019-06-27', '2019-06-28',
               '2019-06-29', '2019-06-30', '2019-07-01', '2019-07-02',
               '2019-07-03', '2019-07-04',
               ...
               '2020-06-16', '2020-06-17', '2020-06-18', '2020-06-19',
               '2020-06-20', '2020-06-21', '2020-06-22', '2020-06-23',
               '2020-06-24', '2020-06-25'],
              dtype='datetime64[ns]', length=367, freq='D')

In [86]:
rango_de_tiempo = pd.date_range(start='25/06/2019', end='25/06/2022', freq='A')
rango_de_tiempo

DatetimeIndex(['2019-12-31', '2020-12-31', '2021-12-31'], dtype='datetime64[ns]', freq='A-DEC')

In [87]:
desc_serie

2020-03-20     cuarentena
2020-03-18    cumpleañito
2020-09-30            hoy
dtype: object

### Filtro por fecha

Usamos un dataset que registra el clima y demás datos para distintas fechas de [alquiler de bicicletas](https://www.kaggle.com/c/bike-sharing-demand/data?select=train.csv).

`pd.read_csv` nos deja leer archivos csv desde una URL. Este dataset esta tambien disponible en el drive de la materia. Leemos el dataset sin bajarlo a un archivo intermedio.

In [88]:
GSPREADHSEET_DOWNLOAD_URL = (
    "https://docs.google.com/spreadsheets/d/{gid}/export?format=csv&id={gid}".format
)

bicis_df = pd.read_csv(
    GSPREADHSEET_DOWNLOAD_URL(gid="1YocUXbrd6uYpOLpU53uMS-AD9To8y_r30KbZdsSSiVQ")
).set_index('datetime')
bicis_df

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
datetime,,,,,,,,,,,
2011-01-01 0:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
2011-01-01 1:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2011-01-01 2:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
2011-01-01 3:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
2011-01-01 4:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336
2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241
2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168
2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129
2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88

In [89]:
bicis_df.loc['2012-12-19 20:00:00']

season          4.0000
holiday         0.0000
workingday      1.0000
weather         1.0000
temp           14.7600
atemp          17.4250
humidity       57.0000
windspeed      15.0013
casual         10.0000
registered    231.0000
count         241.0000
Name: 2012-12-19 20:00:00, dtype: float64

In [90]:
# Para poder quedarnos con un rango de fechas, debemos tener el índice ordenado
bicis_df = bicis_df.sort_index()
bicis_df.loc['2012-11-19 20:00:00':'2012-12-30 20:00:00']

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
datetime,,,,,,,,,,,
2012-11-19 20:00:00,4,0,1,2,15.58,19.695,62,16.9979,7,252,259
2012-11-19 21:00:00,4,0,1,2,15.58,19.695,54,15.0013,15,188,203
2012-11-19 22:00:00,4,0,1,1,13.94,17.425,66,7.0015,7,106,113
2012-11-19 23:00:00,4,0,1,1,13.94,17.425,66,7.0015,2,72,74
2012-11-19 2:00:00,4,0,1,2,14.76,16.665,66,16.9979,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
2012-12-19 5:00:00,4,0,1,1,10.66,14.395,75,6.0032,2,29,31
2012-12-19 6:00:00,4,0,1,1,9.84,12.880,75,6.0032,3,109,112
2012-12-19 7:00:00,4,0,1,1,10.66,13.635,75,8.9981,3,360,363
2012-12-19 8:00:00,4,0,1,1,9.84,12.880,87,7.0015,13,665,678
2012-12-19 9:00:00,4,0,1,1,11.48,14.395,75,7.0015,8,309,317

In [91]:
bicis_df.truncate(before='2012-11-19 22:00:00', after='2012-12-01 00:00:00')
# -

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
datetime,,,,,,,,,,,
2012-11-19 22:00:00,4,0,1,1,13.94,17.425,66,7.0015,7,106,113
2012-11-19 23:00:00,4,0,1,1,13.94,17.425,66,7.0015,2,72,74
2012-11-19 2:00:00,4,0,1,2,14.76,16.665,66,16.9979,0,5,5
2012-11-19 3:00:00,4,0,1,2,14.76,17.425,66,15.0013,0,2,2
2012-11-19 4:00:00,4,0,1,2,14.76,17.425,66,15.0013,1,11,12
2012-11-19 5:00:00,4,0,1,2,14.76,17.425,66,15.0013,1,38,39
2012-11-19 6:00:00,4,0,1,2,14.76,16.665,66,16.9979,3,128,131
2012-11-19 7:00:00,4,0,1,2,14.76,16.665,66,19.9995,5,381,386
2012-11-19 8:00:00,4,0,1,2,14.76,16.665,66,19.9995,13,650,663
2012-11-19 9:00:00,4,0,1,2,14.76,16.665,66,16.9979,18,260,278

### `dt` accessor

In [92]:
# Permite obtener propiedades de tipo fecha de una Series
fechas_series = pd.Series(pd.date_range('2020-09-30 00:00:41', periods=3, freq='s'))
fechas_series

0   2020-09-30 00:00:41
1   2020-09-30 00:00:42
2   2020-09-30 00:00:43
dtype: datetime64[ns]

In [93]:
fechas_series.dt.second

0    41
1    42
2    43
dtype: int64

In [94]:
fechas_series = pd.date_range(
    start='22/06/2019', end='28/06/2019', freq='D'
).to_series()
fechas_series.dt.dayofweek

2019-06-22    5
2019-06-23    6
2019-06-24    0
2019-06-25    1
2019-06-26    2
2019-06-27    3
2019-06-28    4
Freq: D, dtype: int64

# Cómo seguir

La documentación oficial es excelente. Un buen repaso es [10 minutes to pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html) y para profundizar, los links de la izquierda.